
USE COSIF;


INSERT INTO dbo.PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS) VALUES ('P001','Produto 1','A');
INSERT INTO dbo.PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS) VALUES ('P002','Produto 2','A');

INSERT INTO dbo.PRODUTO_COSIF (COD_COSIF, COD_PRODUTO, COD_CLASSIFICACAO, STA_STATUS) VALUES ('C001','P001','Normal','A');
INSERT INTO dbo.PRODUTO_COSIF (COD_COSIF, COD_PRODUTO, COD_CLASSIFICACAO, STA_STATUS) VALUES ('C002','P002','MTM','A');
